export const PushChatTheme = {
  borderRadius: {
    chatViewComponent: '32px',
    chatProfile: '29px',
    messageInput: '29px',
    searchInput: '99px',
    modal: '16px',
    modalInnerComponents: '12px',
    chatBubbleBorderRadius: '12px',
  },

  backgroundColor: {
    chatViewComponentBackground: 'rgba(18, 18, 24, 0.65)',
    chatProfileBackground: 'var(--ifm-color-gray-200)',
    messageInputBackground: 'transparent',
    chatSentBubbleBackground: '#AF3FB1',
    chatReceivedBubbleBackground: 'var(--ifm-color-gray-300)',
    encryptionMessageBackground: 'var(--ifm-color-gray-200)',
    buttonBackground: 'rgb(202, 89, 155)',
    modalBackground: 'var(--ifm-color-gray-500)',
    criteriaLabelBackground: 'rgb(47, 49, 55)',
    modalInputBackground: 'transparent',
    modalHoverBackground: 'rgb(64, 70, 80)',
    buttonDisableBackground: 'var(--ifm-color-neutral-600)',
    toastSuccessBackground:
      'linear-gradient(90.15deg, #30CC8B -125.65%, #30CC8B -125.63%,var(--ifm-color-gray-500) 42.81%)',
    toastErrorBackground:
      'linear-gradient(89.96deg, #FF2070 -101.85%,var(--ifm-color-gray-500) 51.33%)',
    toastShadowBackground: '#00000010',
  },

  fontSize: {
    chatProfileText: '17px',
    messageInputText: '16px',
    chatSentBubbleText: '14px',
    chatReceivedBubbleText: '14px',
    timestamp: '15px',
    // chatBubblesSenderAddressText: '16px',
    encryptionMessageText: '13px',
    chatReceivedBubbleAddressText: '12px',
    chatReceivedBubbleTimestampText: '12px',
    chatSentBubbleTimestampText: '12px',
    searchInputText: '16px',
    searchPlaceholderText: '16px',
  },

  fontWeight: {
    chatProfileText: '500',
    messageInputText: '400',
    chatSentBubbleText: '400',
    chatReceivedBubbleText: '400',
    timestamp: '300',
    // chatBubblesSenderAddressText: '300',
    encryptionMessageText: '400',
    chatReceivedBubbleAddressText: '300',
    chatReceivedBubbleTimestampText: '400',
    chatSentBubbleTimestampText: '400',
    searchInputText: '400',
    searchPlaceholderText: '400',
  },

  fontFamily: 'inherit',

  border: {
    chatViewComponent: '1px solid var(--ifm-color-gray-400)',
    chatProfile: '1px solid var(--ifm-color-gray-400)',
    messageInput: '1px solid var(--ifm-color-gray-400)',
    searchInput: '1px solid transparent',
    modal: 'none',
    modalInnerComponents: '1px solid rgb(74, 79, 103)',
  },

  iconColor: {
    emoji: 'rgba(120, 126, 153, 1)',
    attachment: 'rgba(120, 126, 153, 1)',
    sendButton: 'rgba(120, 126, 153, 1)',
    groupSettings: 'rgba(120, 126, 153, 1)',
  },
  textColor: {
    chatProfileText: 'var(--ifm-color-white)',
    messageInputText: 'rgb(182, 188, 214)',
    chatSentBubbleText: 'var(--ifm-color-white)',
    chatReceivedBubbleText: 'var(--ifm-color-white)',
    timestamp: '#87879A',
    // chatBubblesSenderAddressText: 'rgb(182, 188, 214)',
    encryptionMessageText: 'rgb(182, 188, 214)',
    buttonText: 'var(--ifm-color-white)',
    chatReceivedBubbleAddressText: '#87879A',
    chatReceivedBubbleTimestampText: 'red',
    chatSentBubbleTimestampText: 'red',
    searchInputText: 'var(--ifm-color-white)',
    searchPlaceholderText: 'rgb(101, 119, 149)',
    modalHeadingText: 'var(--ifm-color-white)',
    modalSubHeadingText: 'rgb(182, 188, 214)',
    buttonDisableText: '#B6BCD6',
  },
  backdropFilter: 'blur(6.5px)',
  spinnerColor: 'rgb(202, 89, 155)',
  scrollbarColor: 'rgb(202, 89, 155)',
  // backdropFilter: 'blur(6.5px)',
  // modalBackgroundColor:'rgba(47, 49, 55, 1)',
  // spinnerColor:'rgb(202, 89, 155)',
  // scrollbarColor:'rgb(202, 89, 155)',
  // //the rest param needs to be included in categories
  // modalPrimaryTextColor: '#B6BCD6',
  // modalSearchBarBorderColor: '#4A4F67',
  // modalSearchBarBackground: 'var(--ifm-color-gray-600)',
  // snapFocusBg: '#404650',
  // groupButtonBackgroundColor: 'var(--ifm-color-gray-500)',
  // groupButtonTextColor: 'var(--ifm-color-neutral-600)',
  // modalConfirmButtonBorder: '1px solid var(--ifm-color-neutral-600)',
  // groupSearchProfilBackground: '#404650',
  // modalInputBorderColor: '#4A4F67',
  // snackbarBorderText: '#B6BCD6',
  // snackbarBorderIcon:
  //     'brightness(0) saturate(100%) invert(89%) sepia(8%) saturate(1567%) hue-rotate(191deg) brightness(86%) contrast(93%)',
  // modalContentBackground: 'var(--ifm-color-gray-500)',
  // modalProfileTextColor: '#B6BCD6',
  // toastSuccessBackground:
  //     'linear-gradient(90.15deg, #30CC8B -125.65%, #30CC8B -125.63%, var(--ifm-color-gray-500) 42.81%)',
  // toastErrorBackground:
  //     'linear-gradient(89.96deg, #FF2070 -101.85%, var(--ifm-color-gray-500) 51.33%)',
  // toastShadowColor: '#00000010',
  // toastBorderColor: '#4A4F67',
  // mainBg: 'var(--ifm-color-black)',
  // modalBorderColor: '#4A4F67',
  // modalDescriptionTextColor: 'var(--ifm-color-neutral-600)',
  // modalIconColor: 'var(--ifm-color-neutral-600)',
  // pendingCardBackground: 'rgba(173, 176, 190, 0.08)',
  // modalHeadingColor: '#B6BCD6',
  // defaultBorder: '#4A4F67',
};
