export const darkChatTheme = {
  borderRadius: {
    chatViewComponent: '32px',
    chatProfile: '29px',
    messageInput: '29px',
  },

  backgroundColor: {
    chatViewComponentBackground: 'var(--ifm-color-overlay-black-65)',
    chatProfileBackground: 'var(--ifm-color-gray-200)',
    messageInputBackground: 'var(--ifm-color-transparent)',
    chatSentBubbleBackground: 'var(--ifm-color-chat-sent)',
    chatReceivedBubbleBackground: 'var(--ifm-color-chat-received)',
    encryptionMessageBackground: 'var(--ifm-color-gray-200)',
    buttonBackground: 'var(--ifm-color-button-spinner)',
  },

  fontSize: {
    chatProfileText: '17px',
    messageInputText: '16px',
    chatSentBubbleText: '14px',
    chatReceivedBubbleText: '14px',
    timestamp: '15px',
    chatBubblesSenderAddressText: '16px',
    encryptionMessageText: '13px',
    chatReceivedBubbleAddressText: '12px',
    chatReceivedBubbleTimestampText: '12px',
    chatSentBubbleTimestampText: '12px',
  },

  fontWeight: {
    chatProfileText: '500',
    messageInputText: '400',
    chatSentBubbleText: '400',
    chatReceivedBubbleText: '400',
    timestamp: '300',
    chatBubblesSenderAddressText: '300',
    encryptionMessageText: '400',
    chatReceivedBubbleAddressText: '300',
    chatReceivedBubbleTimestampText: '400',
    chatSentBubbleTimestampText: '400',
  },

  fontFamily: 'inherit',

  border: {
    chatViewComponent: '1px solid var(--ifm-color-gray-400)',
    chatProfile: '1px solid var(--ifm-color-gray-400)',
    messageInput: '1px solid var(--ifm-color-gray-400)',
  },

  iconColor: {
    emoji: 'rgba(120, 126, 153, 1)',
    attachment: 'rgba(120, 126, 153, 1)',
    sendButton: 'rgba(120, 126, 153, 1)',
    groupSettings: 'rgba(120, 126, 153, 1)',
  },
  textColor: {
    chatProfileText: 'var(--ifm-color-white)',
    messageInputText: 'var(--ifm-color-rgb-chat-input)',
    chatSentBubbleText: 'var(--ifm-color-white)',
    chatReceivedBubbleText: 'var(--ifm-color-white)',
    timestamp: 'var(--ifm-color-chat-timestamp)',
    chatBubblesSenderAddressText: 'var(--ifm-color-rgb-chat-input)',
    encryptionMessageText: 'var(--ifm-color-rgb-chat-encryption)',
    buttonText: 'var(--ifm-color-white)',
    chatReceivedBubbleAddressText: 'var(--ifm-color-chat-timestamp)',
    chatReceivedBubbleTimestampText: 'var(--ifm-color-error)',
    chatSentBubbleTimestampText: 'red',
  },
  backdropFilter: 'blur(6.5px)',
  modalBackgroundColor: 'rgba(47, 49, 55, 1)',
  spinnerColor: 'rgb(202, 89, 155)',
  scrollbarColor: 'var(--ifm-color-scrollbar)',
  //the rest param needs to be included in categories
  modalPrimaryTextColor: 'var(--ifm-color-chat-text)',
  modalSearchBarBorderColor: 'var(--ifm-color-chat-border)',
  modalSearchBarBackground: 'var(--ifm-color-gray-600)',
  snapFocusBg: 'var(--ifm-color-chat-bg)',
  groupButtonBackgroundColor: 'var(--ifm-color-gray-500)',
  groupButtonTextColor: 'var(--ifm-color-neutral-600)',
  modalConfirmButtonBorder: '1px solid var(--ifm-color-neutral-600)',
  groupSearchProfilBackground: 'var(--ifm-color-chat-bg)',
  modalInputBorderColor: 'var(--ifm-color-chat-border)',
  snackbarBorderText: 'var(--ifm-color-chat-text)',
  snackbarBorderIcon:
    'brightness(0) saturate(100%) invert(89%) sepia(8%) saturate(1567%) hue-rotate(191deg) brightness(86%) contrast(93%)',
  modalContentBackground: 'var(--ifm-color-gray-500)',
  modalProfileTextColor: 'var(--ifm-color-chat-text)',
  toastSuccessBackground:
    'linear-gradient(90.15deg, var(--ifm-color-success) -125.65%, var(--ifm-color-success) -125.63%, var(--ifm-color-gray-500) 42.81%)',
  toastErrorBackground:
    'linear-gradient(89.96deg, var(--ifm-color-error) -101.85%, var(--ifm-color-gray-500) 51.33%)',
  toastShadowColor: 'var(--ifm-color-overlay-black-10)',
  toastBorderColor: 'var(--ifm-color-chat-border)',
  mainBg: 'var(--ifm-color-black)',
  modalBorderColor: 'var(--ifm-color-chat-border)',
  modalDescriptionTextColor: 'var(--ifm-color-neutral-600)',
  modalIconColor: 'var(--ifm-color-neutral-600)',
  pendingCardBackground: 'rgba(173, 176, 190, 0.08)',
  modalHeadingColor: 'var(--ifm-color-chat-text)',
  defaultBorder: 'var(--ifm-color-chat-border)',
};
