export const HeaderList = {
  testnet: [
    {
      text: 'header.testnet.link1.text',
      subtext: 'header.testnet.link1.subtext',
      title: 'header.testnet.link1.title',
      href: 'https://donut.push.network/',
      id: 'donut',
      target: '_blank',
    },
    {
      text: 'header.testnet.link2.text',
      subtext: 'header.testnet.link2.subtext',
      title: 'header.testnet.link2.title',
      href: 'https://faucet.push.org/',
      id: 'faucet',
      target: '_blank',
    },
  ],
  developers: [
    {
      text: 'header.developers.link1.text',
      subtext: 'header.developers.link1.subtext',
      title: 'header.developers.link1.title',
      href: '/docs',
      target: '_self',
    },
    {
      text: 'header.developers.link2.text',
      subtext: 'header.developers.link2.subtext',
      title: 'header.developers.link2.title',
      href: '/docs/chain/quickstart',
      target: '_self',
    },
    {
      text: 'header.developers.link3.text',
      subtext: 'header.developers.link3.subtext',
      title: 'header.developers.link3.title',
      href: '/docs/chain/tutorials',
      target: '_self',
    },
    {
      text: 'header.developers.link4.text',
      subtext: 'header.developers.link4.subtext',
      title: 'header.developers.link4.title',
      href: 'https://github.com/pushchain',
      target: '_blank',
    },
    {
      text: 'header.developers.link5.text',
      subtext: 'header.developers.link5.subtext',
      title: 'header.developers.link5.title',
      href: 'https://discord.com/invite/pushchain',
      target: '_blank',
    },
    {
      text: 'header.developers.link6.text',
      subtext: 'header.developers.link6.subtext',
      title: 'header.developers.link6.title',
      href: '/docs/chain/ui-kit/examples/',
      target: '_self',
    },
  ],
  community: [
    {
      text: 'header.community.link1.text',
      subtext: 'header.community.link1.subtext',
      title: 'header.community.link1.title',
      href: '/knowledge',
      target: '_self',
    },
    {
      text: 'header.community.link2.text',
      subtext: 'header.community.link2.subtext',
      title: 'header.community.link2.title',
      href: '/knowledge/tokenomics',
      target: '_self',
    },
    {
      text: 'header.community.link3.text',
      subtext: 'header.community.link3.subtext',
      title: 'header.community.link3.title',
      href: 'https://x.com/PushChain',
      target: '_blank',
    },
    {
      text: 'header.community.link4.text',
      subtext: 'header.community.link4.subtext',
      title: 'header.community.link4.title',
      href: 'https://discord.com/invite/pushchain',
      target: '_blank',
    },
    {
      text: 'header.community.link5.text',
      subtext: 'header.community.link5.subtext',
      title: 'header.community.link5.title',
      href: 'https://t.me/epnsproject',
      target: '_blank',
    },
  ],
  resources: [
    {
      text: 'header.resources.link1.text',
      subtext: 'header.resources.link1.subtext',
      title: 'header.resources.link1.title',
      href: '/blog',
      target: '_self',
    },
    {
      text: 'header.resources.link2.text',
      subtext: 'header.resources.link2.subtext',
      title: 'header.resources.link2.title',
      href: '/litepaper.pdf',
      target: '_blank',
    },
    {
      text: 'header.resources.link3.text',
      subtext: 'header.resources.link3.subtext',
      title: 'header.resources.link3.title',
      href: '/knowledge/faq',
      target: '_self',
    },
  ],
};
