export const InvList = {
  top: [
    {
      srcref: 'jump',
      id: 'jump',
      title: null,
      subtitle: null,
      alt: 'Jump',
    },
    {
      srcref: 'parafi',
      id: 'parafi',
      title: null,
      subtitle: null,
      alt: 'ParaFi',
    },
    {
      srcref: 'vcAndrew',
      id: 'andrew',
      title: null,
      subtitle: null,
      alt: 'Andrew Keys',
    },
    {
      srcref: 'true',
      id: 'true',
      title: null,
      subtitle: null,
      alt: 'True',
    },
    {
      srcref: 'iosg',
      id: 'iosg',
      title: null,
      subtitle: null,
      alt: 'IOSG',
    },
    {
      srcref: '4rc',
      id: '4rc',
      title: null,
      subtitle: null,
      alt: '4RC',
    },
    {
      srcref: 'vcSandeep',
      id: 'sandeep',
      title: null,
      subtitle: null,
      alt: 'Sandeep',
    },
    {
      srcref: 'aCapital',
      id: 'a_capital',
      title: null,
      subtitle: null,
      alt: 'A Capital',
    },
    {
      srcref: 'thelao',
      id: 'thelao',
      title: null,
      subtitle: null,
      alt: 'The LAO',
    },
    {
      srcref: 'vcKenneth',
      id: 'kenneth',
      title: null,
      subtitle: null,
      alt: 'Kenneth Ng',
    },
  ],
  bottom: [
    {
      srcref: 'tigerglobal',
      id: 'tigerglobal',
      title: null,
      subtitle: null,
      alt: 'Tiger Global',
    },
    {
      srcref: 'vcDefi-dad',
      id: 'defi-dad',
      title: null,
      subtitle: null,
      alt: 'Defi dad',
    },
    {
      srcref: 'binance',
      id: 'binancelabs',
      title: null,
      subtitle: null,
      alt: 'Binance Labs',
    },
    {
      srcref: 'vcBalaji',
      id: 'balaji',
      title: null,
      subtitle: null,
      alt: 'Balaji Srinivasan',
    },
    {
      srcref: 'polygon-studios',
      id: 'polygonstudios',
      title: null,
      subtitle: null,
      alt: 'Polygon Studios',
    },
    {
      srcref: 'sino',
      id: 'sino',
      title: null,
      subtitle: null,
      alt: 'Sino Global Capital',
    },
    {
      srcref: 'vcAnton',
      id: 'anton',
      title: null,
      subtitle: null,
      alt: 'Anton Bukov',
    },
    {
      srcref: 'zee-prime',
      id: 'zee-prime',
      title: null,
      subtitle: null,
      alt: 'Zee Prime',
    },
    {
      srcref: 'signum',
      id: 'signum',
      title: null,
      subtitle: null,
      alt: 'Signum Capital',
    },
    {
      srcref: 'vcScott',
      id: 'scott',
      title: null,
      subtitle: null,
      alt: 'Scott Moore',
    },
  ],
};
