export const ShowcaseList = {
  top: {
    left: {
      upper: [
        {
          srcref: 'bankless',
          logoname: 'Bankless',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'decentraland',
          logoname: 'Decentraland',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'shapeshift',
          logoname: 'Shapeshift',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'uniswap',
          logoname: 'Uniswap',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'oasis',
          logoname: 'Oasis',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
    mid: {
      upper: [
        {
          srcref: 'snapshot',
          logoname: 'Snapshot',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'ens',
          logoname: 'ENS',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'bancor',
          logoname: 'Bancor',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'aragon',
          logoname: 'Aragon',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'makerdao',
          logoname: 'MakerDAO',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'earnifi',
          logoname: 'EarniFi',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'cryptocurrencyjobs',
          logoname: 'Cryptocurrency Jobs',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'aave',
          logoname: 'AAVE',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'rekt',
          logoname: 'Rekt',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
  },
  bottom: {
    left: {
      upper: [
        {
          srcref: 'metastable',
          logoname: 'Meta Stable',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: '1inch',
          logoname: '1Inch',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'secondlive',
          logoname: 'Second Live',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'atlendis',
          logoname: 'Atlendis',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'apeswap',
          logoname: 'Apeswap',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
    mid: {
      upper: [
        {
          srcref: 'qidao',
          logoname: 'QiDAO',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'dydx',
          logoname: 'DyDx',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'lepasametaverse',
          logoname: 'Lepasa Metaverse',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'orionprotocol',
          logoname: 'Orion Protocol',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'symphonyfinance',
          logoname: 'Symphony Finance Labs',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'coindesk',
          logoname: 'Coindesk',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'kybernetwork',
          logoname: 'Kyber Network',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'lifi',
          logoname: 'LiFi Protocol',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'dd',
          logoname: 'Developer DAO',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
  },
  left: {
    left: {
      upper: [
        {
          srcref: 'unstoppable',
          logoname: 'Unstoppable Domains',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'mahadao',
          logoname: 'MahaDAO',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'proofofhumanity',
          logoname: 'Proof of Humanity',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'sushi',
          logoname: 'Sushiswap',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
  },
  right: {
    left: {
      upper: [
        {
          srcref: 'polychainmonsters',
          logoname: 'Polychain Monsters',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'pooltogether',
          logoname: 'Pool Together',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'ethsign',
          logoname: 'ETHSign',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'diamante',
          logoname: 'Diamante',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
  },
};

export const ShowcaseResponsiveList = {
  top: [
    {
      srcref: 'bankless',
      logoname: 'Bankless',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'decentraland',
      logoname: 'Decentraland',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'uniswap',
      logoname: 'Uniswap',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'aave',
      logoname: 'AAVE',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'rekt',
      logoname: 'Rekt',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'sushi',
      logoname: 'Sushiswap',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'unstoppable',
      logoname: 'Unstoppable Domains',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'proofofhumanity',
      logoname: 'Proof of Humanity',
      width: '96px',
      height: '96px',
      class: '',
    },
  ],
  bottom: [
    {
      srcref: 'diamante',
      logoname: 'Diamante',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: '1inch',
      logoname: '1Inch',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'coindesk',
      logoname: 'Coindesk',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'ens',
      logoname: 'ENS',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'bancor',
      logoname: 'Bancor',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'aragon',
      logoname: 'Aragon',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'qidao',
      logoname: 'QiDAO',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'dydx',
      logoname: 'DyDx',
      width: '96px',
      height: '96px',
      class: '',
    },
  ],
};

// Additional showcase list
// [
//   {
//     srcref: 'anglelabs',
//    logoname: 'Angle Labs',
//   },
//   {
//     srcref: 'flipside',
//    logoname: 'Flipside',
//   },
//   {
//     srcref: 'goodghosting',
//    logoname: 'Good Ghosting',
//   },
//   {
//     srcref: 'gro',
//    logoname: 'Gro',
//   },
//   {
//     srcref: 'meanfinance',
//    logoname: 'Mean Finance',
//   },
//   {
//     srcref: 'mover',
//    logoname: 'Mover',
//   },
//   {
//     srcref: 'podsfinance',
//    logoname: 'Pods Finance',
//   },
//   {
//     srcref: 'thena',
//    logoname: 'Thena',
//   },
//   {
//     srcref: 'wormbat',
//    logoname: 'Wormbat',
//   },
//   {
//     srcref: 'zeroswap',
//    logoname: 'Zeroswap',
//   },
// ]
