export const SupportedLanguagesList = [
  {
    language: 'English',
    srcref: 'en',
    id: 'en',
    ctatitle: 'Change language to English',
    ctatext: 'English',
  },
  {
    language: 'Chinese Simplified',
    srcref: 'zh-CN',
    id: 'zh-CN',
    ctatitle: '切换语言为中文',
    ctatext: '中文',
  },
  {
    language: 'Spanish',
    srcref: 'es',
    id: 'es',
    ctatitle: 'Cambiar el idioma a español',
    ctatext: 'Español',
  },
  {
    language: 'Hindi',
    srcref: 'hi',
    id: 'hi',
    ctatitle: 'भाषा को हिंदी में बदलें',
    ctatext: 'हिंदी',
  },
  {
    language: 'Japanese',
    srcref: 'ja',
    id: 'ja',
    ctatitle: '言語を日本語に変更する',
    ctatext: '日本語',
  },
  {
    language: 'Korean',
    srcref: 'ko',
    id: 'ko',
    ctatitle: '한국어로 언어 변경',
    ctatext: '한국어',
  },
  {
    language: 'Portuguese',
    srcref: 'pt',
    id: 'pt',
    ctatitle: 'Mudar o idioma para português',
    ctatext: 'Português',
  },
  {
    language: 'Russian',
    srcref: 'ru',
    id: 'ru',
    ctatitle: 'Изменить язык на русский',
    ctatext: 'Русский',
  },
  {
    language: 'Turkish',
    srcref: 'tr',
    id: 'tr',
    ctatitle: 'Dili Türkçeye değiştir',
    ctatext: 'Türkçe',
  },
  {
    language: 'French',
    srcref: 'fr',
    id: 'fr',
    ctatitle: 'Changer la langue en français',
    ctatext: 'Français',
  },
  {
    language: 'Indonesian',
    srcref: 'id',
    id: 'id',
    ctatitle: 'Ubah bahasa ke bahasa Indonesia',
    ctatext: 'Bahasa Indonesia',
  },
  {
    language: 'Vietnamese',
    srcref: 'vi',
    id: 'vi',
    ctatitle: 'Thay đổi ngôn ngữ sang tiếng Việt',
    ctatext: 'Tiếng Việt',
  },
  {
    language: 'German',
    srcref: 'de',
    id: 'de',
    ctatitle: 'Sprache auf Deutsch ändern',
    ctatext: 'Deutsch',
  },
  {
    language: 'Arabic',
    srcref: 'ar',
    id: 'ar',
    ctatitle: 'تغيير اللغة إلى العربية',
    ctatext: 'العربية',
  },
];
