name: Deploy PR preview to pr-1067

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - main

concurrency: preview-1067

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        run: |
          echo "REACT_APP_PREVIEW_BASE=pr-1067" >> $GITHUB_ENV
          echo "REACT_APP_DEPLOY_ENV=PREVIEW" >> $GITHUB_ENV
          echo "REACT_APP_PUBLIC_URL=https://push-protocol.github.io" >> $GITHUB_ENV
          echo "GITHUB_PR_NUMBER=1067" >> $GITHUB_ENV
          echo "REACT_APP_BASE_URL=/push-chain-website/pr-preview/pr-1067" >> $GITHUB_ENV

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Corepack & Yarn 4.2.2
        run: |
          corepack enable
          corepack prepare yarn@4.2.2 --activate
          yarn --version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          yarn install
          yarn build:pr:preview

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: ./build/
          umbrella-dir: pr-preview
          subdir: pr-1067

      - name: Remove preview on close
        uses: rossjrw/pr-preview-action@v1.4.7
        if: github.event.action == 'closed' || github.event.pull_request.merged
        with:
          source-dir: ./build/
          umbrella-dir: pr-preview
          # subdir: pr-1067
          # action: remove
